# DROP TABLE IF EXISTS CITY;

# CREATE TABLE CITY(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(30), STATE VARCHAR(5), COUNTRY VARCHAR(10));

# INSERT INTO CITY(NAME, STATE, COUNTRY) VALUES('Rubin', '1', 'CN');